### ISSUE TITLE
world_aligned_auto_uv missing dependacy HDA

### ISSUE THREAD

**Issue by vinyvince** [faxcorp/HDA-s-for-gamedev-Unreal-engine#1]
Hello.

I wanted to test how your method differs from my try, this HDA is asking for "align_vertex_uv_islands_by_3D_direction.hda" which is not provided. Or did i miss something?

Cheers

**Comment by faxlab** [comment]
Hi, thanks. I moved out the nodes from missing HDA and I used this post as reference https://www.sidefx.com/forum/topic/88219/#post-381122 you probably want to study that
My variant is tuned for hard surface you might want to add seams yourself. By the way if you have any other methods I'd be curious to find out
